---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть протестирован на совместимость со старыми версиями браузеров.
  - Сайт должен быть SPA-приложением.
  - Сайт должен иметь защищенное https -соединение.
  - Сайт должен быть доступен для людей с ограниченными возможностями.
  - Сумма стоимости товара в корзине должна округляться в соответствии с принятыми нормами.
  - Сайт должен корректно (перевод) работать в двухязычном варианте (русский и английский).
  - Другие пользователи не должны иметь возможноть просматривать чужие корзины.
  - Шрифт текста должен быть комфортным при работе сайта на мобильном устройстве.
