---
functional:
  - 1  Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - 2  Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - 3  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - 4  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - 5  Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - 6  Сайт должен быть безопасным и защищать данные пользователя.
  - 7  Сайт должен иметь мобильную версию.
  - 8  Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - 9  Сайт должен быть способен обрабатывать большое количество трафика.
  - 10 Сайт должен быть доступен на различных устройствах.
implicit:
  - 11 Сайт должен быть протестирован на совместимость со старыми версиями браузеров.
  - 12 Сайт должен иметь защищенное https -соединение.
  - 13 Сайт должен быть доступен для людей с ограниченными возможностями.
  - 14 Сумма стоимости товара в корзине должна округляться в соответствии с принятыми нормами.
  - 15 Элементы сайта должны корректно (одинаково) отображаться в двухъязычном варианте (русский и английский).
  - 16 Другие пользователи не должны иметь возможноть просматривать чужие корзины.
  - 17 Шрифт текста должен быть комфортным при работе сайта на мобильном устройстве.
  - 18 Набор ключевых слов при поиске товаров.
  - 19 Товар в корзине должен соответствовать тому, что выбрал пользователь.
